name: GitHub-Profile-Summary-Cards

on:
  schedule: # execute every 1 week
    - cron: "* */168 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_SECRETS }}
        with:
          USERNAME: ${{ github.repository_owner }}
